# version: "3.8"
services:
  fastapi:
    build:
      context: ./fastapi_app
    container_name: fastapi
    volumes:
      - ./shared:/app/shared  # Shared directory for file uploads      
    ports:
      - "8000:80"
    depends_on:
      - filebrowser

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ./shared:/srv  # Shared directory with FastAPI
      - ./Resources/branding:/branding 
    ports:
      - "8080:80"
    environment:
      - FB_AUTH_METHOD=none  # Adjust authentication settings as needed
      - FB_BRANDING=/branding  # Point to branding directory
