FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /app

# Copy the FastAPI app to the container
COPY . .

# Install any required dependencies (if needed)
# RUN pip install -r requirements.txt
